version: "3.7"
services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "8883:8883"
    volumes:
      - ./config:/mosquitto/config:rw
      - ./log:/mosquitto/log:rw

volumes:
  config:
  log:

networks:
  default:
    name: mqtt5-network
