version: "3.7"
services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    network_mode: host
    ports:
      - "53165:53165"
    volumes:
      - ./config:/mosquitto/config:rw
      - ./log:/mosquitto/log:rw

# volumes for mapping data,config and log
volumes:
  config:
  log:

networks:
  default:
    name: mqtt5-network